version: '3'

networks:
    laravel:

services:
    nginx:
        container_name: nginx
        image: nginx:stable-alpine #the image we want to run in this container
        ports:
            - '8000:80'
        volumes: #Kinda like symlinks
            - ./app:/var/www:cached
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: #these containers needs to be running before we can run the nginx container
            - php
            - mysql
            - redis
        networks: #Attached to the laravel network
            - laravel

    workspace: #used for running artisan commands without docker-compose exec everytime. Just do 'docker-compose exec workspace bash' once
        container_name: workspace
        build:
            context: https://github.com/laradock/laradock.git#:workspace
            args:
                INSTALL_XDEBUG: "true"
                INSTALL_NODE: "true"
                LARADOCK_PHP_VERSION: "7.4"
        volumes:
            - ./app:/var/www:cached
        depends_on:
            - php
            - mysql
            - redis
        networks:
            - laravel

    mysql:
        container_name: mysql
        image: mysql:5.7.22
        restart: unless-stopped
        tty: true
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql #this will be the host in laravel .env file
        networks:
            - laravel
    php:
        container_name: php
        build: #instead of an image, we are going to build this container from a local image
            context: . #the project where our dockerfile is located
            dockerfile: Dockerfile #the dockerfile
        volumes:
            - ./app:/var/www:cached
        ports:
            - '9001:9001'
        networks:
            - laravel

    redis:
        container_name: redis
        image: redis:alpine
        ports:
            - "6379:6379"
